FIX
account_invoice_rounding/models/account.py", line 102, in _compute_swedish_rounding
    if round_method[:7] != 'swedish':
TypeError: 'bool' object has no attribute '__getitem__'

when no rounding method is set